# Generated by Django 4.2.7 on 2023-12-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muala', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
